Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tidychef import acquire
from tidychef.selection import XlsxSelectable

table: XlsxSelectable = acquire.xlsx.http("https://github.com/mikeAdamss/tidychef/raw/main/tests/fixtures/xlsx/ons-oic.xlsx", tables="Table 3a")
table.excel_ref('A1:A2').assert_one()
------------------


[31m---------------------------------------------------------------------------[39m
[31mAssertionError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[3][39m[32m, line 5[39m
[32m      2[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mtidychef[39;00m[34;01m.[39;00m[34;01mselection[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m XlsxSelectable
[32m      4[39m table: XlsxSelectable = acquire.xlsx.http([33m"[39m[33mhttps://github.com/mikeAdamss/tidychef/raw/main/tests/fixtures/xlsx/ons-oic.xlsx[39m[33m"[39m, tables=[33m"[39m[33mTable 3a[39m[33m"[39m)
[32m----> [39m[32m5[39m [43mtable[49m[43m.[49m[43mexcel_ref[49m[43m([49m[33;43m'[39;49m[33;43mA1:A2[39;49m[33;43m'[39;49m[43m)[49m[43m.[49m[43massert_one[49m[43m([49m[43m)[49m

[36mFile [39m[32m~/.pyenv/versions/3.12.11/lib/python3.12/site-packages/tidychef/selection/selectable.py:74[39m, in [36mSelectable.assert_one[39m[34m(self)[39m
[32m     70[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34massert_one[39m([38;5;28mself[39m):
[32m     71[39m [38;5;250m    [39m[33;03m"""[39;00m
[32m     72[39m [33;03m    Assert that the current selection contains exactly one cell[39;00m
[32m     73[39m [33;03m    """[39;00m
[32m---> [39m[32m74[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43massert_len[49m[43m([49m[32;43m1[39;49m[43m)[49m

[36mFile [39m[32m~/.pyenv/versions/3.12.11/lib/python3.12/site-packages/tidychef/selection/selectable.py:66[39m, in [36mSelectable.assert_len[39m[34m(self, number_of_cells)[39m
[32m     60[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34massert_len[39m([38;5;28mself[39m, number_of_cells: [38;5;28mint[39m):
[32m     61[39m [38;5;250m    [39m[33;03m"""[39;00m
[32m     62[39m [33;03m    Assert that the current selection contains the number of cells[39;00m
[32m     63[39m [33;03m    specified[39;00m
[32m     64[39m [33;03m    """[39;00m
[32m     65[39m     [38;5;28;01massert[39;00m (
[32m---> [39m[32m66[39m         [38;5;28mlen[39m([38;5;28mself[39m.cells) == number_of_cells
[32m     67[39m     ), [33mf[39m[33m"[39m[33mSelection contains [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m([38;5;28mself[39m.cells)[38;5;132;01m}[39;00m[33m cells, not [39m[38;5;132;01m{[39;00mnumber_of_cells[38;5;132;01m}[39;00m[33m"[39m
[32m     68[39m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m

[31mAssertionError[39m: Selection contains 2 cells, not 1

